// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HvacUIClient is the client API for HvacUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HvacUIClient interface {
	// ListCoolerSpecs returns a list of Cooler(s) that can be started through the UI.
	ListCoolerSpecs(ctx context.Context, in *ListCoolerSpecsRequest, opts ...grpc.CallOption) (HvacUI_ListCoolerSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type hvacUIClient struct {
	cc grpc.ClientConnInterface
}

func NewHvacUIClient(cc grpc.ClientConnInterface) HvacUIClient {
	return &hvacUIClient{cc}
}

func (c *hvacUIClient) ListCoolerSpecs(ctx context.Context, in *ListCoolerSpecsRequest, opts ...grpc.CallOption) (HvacUI_ListCoolerSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &HvacUI_ServiceDesc.Streams[0], "/v1.HvacUI/ListCoolerSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &hvacUIListCoolerSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HvacUI_ListCoolerSpecsClient interface {
	Recv() (*ListCoolerSpecsResponse, error)
	grpc.ClientStream
}

type hvacUIListCoolerSpecsClient struct {
	grpc.ClientStream
}

func (x *hvacUIListCoolerSpecsClient) Recv() (*ListCoolerSpecsResponse, error) {
	m := new(ListCoolerSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hvacUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.HvacUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HvacUIServer is the server API for HvacUI service.
// All implementations must embed UnimplementedHvacUIServer
// for forward compatibility
type HvacUIServer interface {
	// ListCoolerSpecs returns a list of Cooler(s) that can be started through the UI.
	ListCoolerSpecs(*ListCoolerSpecsRequest, HvacUI_ListCoolerSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedHvacUIServer()
}

// UnimplementedHvacUIServer must be embedded to have forward compatible implementations.
type UnimplementedHvacUIServer struct {
}

func (UnimplementedHvacUIServer) ListCoolerSpecs(*ListCoolerSpecsRequest, HvacUI_ListCoolerSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListCoolerSpecs not implemented")
}
func (UnimplementedHvacUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedHvacUIServer) mustEmbedUnimplementedHvacUIServer() {}

// UnsafeHvacUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HvacUIServer will
// result in compilation errors.
type UnsafeHvacUIServer interface {
	mustEmbedUnimplementedHvacUIServer()
}

func RegisterHvacUIServer(s grpc.ServiceRegistrar, srv HvacUIServer) {
	s.RegisterService(&HvacUI_ServiceDesc, srv)
}

func _HvacUI_ListCoolerSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListCoolerSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HvacUIServer).ListCoolerSpecs(m, &hvacUIListCoolerSpecsServer{stream})
}

type HvacUI_ListCoolerSpecsServer interface {
	Send(*ListCoolerSpecsResponse) error
	grpc.ServerStream
}

type hvacUIListCoolerSpecsServer struct {
	grpc.ServerStream
}

func (x *hvacUIListCoolerSpecsServer) Send(m *ListCoolerSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _HvacUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HvacUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.HvacUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HvacUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HvacUI_ServiceDesc is the grpc.ServiceDesc for HvacUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HvacUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.HvacUI",
	HandlerType: (*HvacUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _HvacUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListCoolerSpecs",
			Handler:       _HvacUI_ListCoolerSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hvac-ui.proto",
}
